CREATE TABLE IF NOT EXISTS posts(
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    body TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS clocks(
    id SERIAL PRIMARY KEY,
    clockIn TIMESTAMPTZ NOT NULL,
    clockOut TIMESTAMPTZ
);